---

- hosts: linux
  become: true
  tasks:
  - name: Clean the local repository
    apt:
     autoclean: yes
  
  - name: Remove unsused dependency packages for all modules
    apt:
     autoremove: yes
